REM batch file to clean out extra ADMB-produced files
del *.p0*
del *.b0*
del *.r0*
del *.std
del *.htp
del *.eva
del *.tds
del *.bar
del *.cov
del *.dep
del *.hes
del *.rpt
del *.rep
del *.cpp
del *.log
del *.obj
del *.tmp
del *.ecm
del *.mc2
del *.mcm
del *.hst
del *.psv
del gradient.*
del tmp_admb
del variance
del SIS_table.sso
del rebuild.sso
del posterior_obj_func.sso
del posterior_vectors.sso                  
del posteriors.sso                         
del ParmTrace.sso
del runnumber.ss
